export const NEW_CONTACT_FORM = "NEW_CONTACT_FORM";
export const EXISTING_CONTACT_SEARCH = "EXISTING_CONTACT_SEARCH";
export const CONTACT_DETAILS = "CONTACT_DETAILS";
export const CHAT_DETAILS_FORM = "CHAT_DETAILS_FORM";
export const SHOW_CONTACT_FLAG = "SHOW_CONTACT_FLAG";
export const SHOW_CHAT_WINDOW = "SHOW_CHAT_WINDOW";
export const SHOW_CHAT_MESSAGE_DETAILS = "SHOW_CHAT_MESSAGE_DETAILS";
export const GLOBAL_CHAT_STORE = "GLOBAL_CHAT_STORE";
